[project]
name = "phc-nzi"
version = "0.1.0"
description = "Modular MPB configuration, HPC runner, frequency extractor, HDF5 grid transformer, and plotter package for photonic crystal calculations"
readme = "README.md"
authors = [
    { name = "Enrico Vallar", email = "s232699@dtu.dk" }
]
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.5.0",
    "numpy>=1.20.0",
    "h5py>=3.0.0",
    "scikit-optimize>=0.10.2",
    "pyyaml>=6.0.3",
    "joblib>=1.5.3",
    "tqdm>=4.70.0",
]

[project.scripts]
phc-init = "phc_nzi.init:main"
phc-runner = "phc_nzi.runner:main"
phc-extractor = "phc_nzi.extractor:main"
phc-plotter = "phc_nzi.plotter:main"
phc-transformer = "phc_nzi.transformer:main"
phc-rectifier = "phc_nzi.transformer:main"
phc-bo = "phc_nzi.bo:main"


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
